services:
  pihole:
    container_name: pihole
    build:
      context: ./config
    image: pihole/pihole:latest_https
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      # Required UID/USER for running pihole in a docker container 
      PIHOLE_UID: '0'
      DNSMASQ_USER: 'root'
      PIHOLE_DNS_: '172.28.2.3'
      DNSSEC: 'true'
      WEBTHEME: 'default-dark'
      VIRTUAL_HOST: ${LOCAL_USER}
      HTTPS_PORT: '443'
      IP: ${LOCAL_IP}
      SSH_USER: ${SSH_USER}
      SSH_IP: ${SSH_IP}
      SSH_PORT: ${SSH_PORT}
      LOGKEEPDAYS: ${LOGKEEPDAYS}
    ### https://github.com/pi-hole/docker-pi-hole  
    ### Can mount volumes, although there is a known bug where pihole start up scripts
    ### while change the permissions,users, and groups on somefiles making them inaccasable...
    ### In the run script ive added a workaround as mentioned here: https://github.com/pi-hole/docker-pi-hole/issues/610#issuecomment-922832145
    ### In the case server has a scheduled reboot regularly, all the following line to your cron job a few minites after the scheduled reboot: 
    ### docker exec pihole /bin/bash -c "chmod 755 -R /etc/pihole/ /etc/dnsmasq.d && chown -R root.pihole /etc/pihole/ /etc/dnsmasq.d;"
    volumes:
      - /pihole/settings:/etc/pihole:rw
      - /pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - ./data/certs:/etc/lighttpd/certs
      - /pihole/log:/var/log/pihole-gemini:rw
    restart: unless-stopped
    #cap_add:
    #  - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    networks:
      pihole-net:
        ipv4_address: 172.28.2.2
        aliases:
          - pihole
          
  unbound:
    container_name: unbound
    image: klutchell/unbound
    volumes:
      - ./data/custom.conf.d:/etc/unbound/custom.conf.d
    restart: unless-stopped
    networks:
      pihole-net:
        ipv4_address: 172.28.2.3
        aliases:
          - unbound

networks:
  pihole-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.2.0/24