FROM pihole/pihole:latest

RUN echo -e '\n\
#Loading openssl \n\
server.modules += ( "mod_openssl" ) \n\
\n\
setenv.add-environment = ("fqdn" => "true") \n\
$SERVER["socket"] == ":443" { \n\
	ssl.engine  = "enable" \n\
	ssl.pemfile = "/etc/lighttpd/certs/server.pem" \n\
	ssl.openssl.ssl-conf-cmd = ("MinProtocol" => "TLSv1.3", "Options" => "-ServerPreference") \n\
} \n\
# Redirect HTTP to HTTPS \n\
$HTTP["scheme"] == "http" { \n\
	$HTTP["host"] =~ ".*" { \n\
		url.redirect = (".*" => "https://%0$0") \n\
		url.redirect-code = 308 \n\
	} \n\
}' >> /etc/lighttpd/lighttpd.conf

COPY pihole-gemini-standby.sh /usr/local/bin/pihole-gemini

RUN sed -i '$ d' /opt/pihole/gravity.sh

RUN echo -e '\n\
su -c /usr/local/bin/pihole-gemini - pi \n\
"${PIHOLE_COMMAND}" status' >> /opt/pihole/gravity.sh
