FROM pihole/pihole:latest

COPY pihole-gemini.sh /usr/local/bin/pihole-gemini

RUN sed -i '/piholeDir="\/etc\/${basename}"/a chmod 755 -R "${piholeDir}" "\/etc\/dnsmasq.d"\nchown -R root.pihole "${piholeDir}" "\/etc\/dnsmasq.d"\n' /opt/pihole/gravity.sh; \
    sed -i '$ d' /opt/pihole/gravity.sh; \
    echo -e '\n\
    /usr/local/bin/pihole-gemini \n\
    "${PIHOLE_COMMAND}" status' >> /opt/pihole/gravity.sh; \
    chmod +x /usr/local/bin/pihole-gemini; \
    apt update && apt install rsync openssh-client -y